language: python
python:
  - "3.6"
#  - "3.7" # travis doesn't support 3.7 yet.
before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940
  - export BOTO_CONFIG=/dev/null
# command to install dependencies
install:
  - pip install .[test]
# command to run tests
script:
  - pip list
  - pytest # or py.test for Python versions 3.5 and below
